### ISSUE TITLE
not compatible with esphome >= 2025.2

### ISSUE THREAD

**Issue by Spartan-II-117** [digiblur/ESPHome_LOHAS_LED#10]
ESPHome has removed support for custom components in 2025.2 can this be updated to use the new external component mechanism?

**Comment by GsynthChris** [comment]
Ironic that you just posted this cause I was also working on solving this problem. 
I changed the config to use a template instead on the custom function

I just used this and its working!

```
esphome:
  name: ledbedroomdoor
  friendly_name: Bedroom Door

esp8266:
  board: esp01_1m
  restore_from_flash: true

wifi:
  ssid: "yourwifi"
  password: "your-password"
  use_address: 192.168.xx.xx

logger:
api:
ota:
  - platform: esphome
web_server:
  port: 80

my9231:
 data_pin: GPIO13  
 clock_pin: GPIO15  
 num_channels: 6
 num_chips: 2 
 
output:
  - platform: my9231
    id: output_blue
    channel: 3
  - platform: my9231
    id: output_red
    channel: 5
  - platform: my9231
    id: output_green
    channel: 4
  - platform: my9231
    id: output_cw1
    channel: 1
  - platform: my9231
    id: output_cw2
    channel: 2
  - platform: template
    id: cw
    type: float
    write_action:
      - output.set_level:
          id: output_cw1
          level: !lambda 'return state;'
      - output.set_level:
          id: output_cw2
          level: !lambda 'return state;'

light:
  - platform: rgbw
    name: "Bedroom2"
    default_transition_length: 0s
    red: output_red
    green: output_green
    blue: output_blue
    white: cw
```
