### ISSUE TITLE
Lohas BR30 and 6" downlight RGBW doesn't retain state after power cycling.

### ISSUE THREAD

**Issue by farfarfromhome** [digiblur/ESPHome_LOHAS_LED#2]
@digiblur 
I am a Newbie and I would like to commend you on your utube video explaining tuya convert and ESPHome yaml for the Lohas bulbs.  They were at a perfect level for my understanding!  I have a Lohas br30 and 6" downlights which both have an additional channel of CW which I was able to get running by modifying your code as follows:

copychan.h
`using namespace esphomelib::output;

class CopyOutput : public FloatOutput {
 public:
  FloatOutput *channel_a;
  FloatOutput *channel_b;
  FloatOutput *channel_c;

  void write_state (float state) override {
    channel_a->set_level (state);
    channel_b->set_level (state);
    channel_c->set_level (state);
  }
};
`

lohasbr30.yaml
`my9231:
 data_pin: GPIO13
 clock_pin: GPIO15
 num_channels: 6
 num_chips: 2
 update_on_boot: TRUE

output:
  - platform: my9231
    id: output_blue
    channel: 3
  - platform: my9231
    id: output_red
    channel: 5
  - platform: my9231
    id: output_green
    channel: 4
  - platform: my9231
    id: output_cw1
    channel: 0
  - platform: my9231
    id: output_cw2
    channel: 1
  - platform: my9231
    id: output_cw3
    channel: 2
  - platform: custom
    type: float
    lambda: |-
      auto *copy = new CopyOutput();
      copy->channel_a = id(output_cw1);
      copy->channel_b = id(output_cw2);
      copy->channel_c = id(output_cw3);
      return {copy}; 
    outputs:
    - id: cw
`

However I cannot figure out how to make the bulb turn on to the previous setting after switching off and on with the normal light switch per Tasmoto operation.  I tried both TRUE and FALSE for the update_on_boot setting to no avail and cannot find anything else in the ESPHome documentation.  Is this an issue or just a Newbie user error?

**Comment by digiblur** [comment]
That is one downside I found as well as it always defaults to off for me as well.  I searched a few threads on Esphome but I didn't see anything about lights really being implemented, it seemed to be for the relay.  

You might try to ask others in the ESPHome discord channel to see if there are workarounds they've found:  https://discord.gg/KhAMKrd

Thanks for sharing the config!  Sounds like that light is pretty bright with 3 banks of CW!

**Comment by farfarfromhome** [comment]
I posted on discord as you suggested.  Hopefully someone responds.  If not maybe there is a way to add a lambda to always copy the last state to flash and then another lambda to read and set on power up.  Unfortunately I have no experience with this.

 

Yes, two banks were already blinding me while I tried to get the code running for the third.  I am new to this but I am proud that I managed to complete a pool controller using a pi, node red, and mqtt.  I really like node red and am not so sure about HA and yaml yet.  EspHome does seem intriguing for the customization capability so running via mqtt directly from node red may be easier for me.  Ultimately I would like to fit an ESP8266 into the pool valves to provide proportional control via wifi from the pi.

**Comment by digiblur** [comment]
Going to try this one later and let you know.

https://esphome.io/components/esphome.html#esp8266-restore-from-flash

**Comment by buckyfan** [comment]
Did anyone manage to get the BR30 version of this bulb working? I tried to use the modified 3chan file without any success. Doesn't respond even with wrong color information. Also tried the PWM version without any luck.

Link: https://smile.amazon.com/gp/product/B07YKQL92Y/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

**Comment by farfarfromhome** [comment]
Hi Buckyfan

 

Yes I did have the BR30 working until I inadvertently bricked it by turning on the ESPhome verbose logging!  I attach my yaml with the verbose logging removed.  The header file needs to be the latest per digiblur post.

 

I have many Lohas 6” downlights which have exactly the same internal components and are working very well for me.

 

Were you able to tuya convert?  My device was purchased before the tuya update so the original tuya convert worked fine.  Several of my 6” downlights did not convert with the original tuya convert but the latest tuya convert worked OK.  My process was to tuya convert to Tasmoto, and use Tasmoto to download the esphome bin.

 

If you can give more detail of you exact process and problem I can perhaps help more?

**Comment by farfarfromhome** [comment]
From: Barry Roberts [mailto:barryrroberts@comcast.net] 
Sent: Thursday, January 9, 2020 9:15 AM
To: 'digiblur/ESPHome_LOHAS_LED'; 'digiblur/ESPHome_LOHAS_LED'
Cc: 'Author'
Subject: RE: [digiblur/ESPHome_LOHAS_LED] Lohas BR30 and 6" downlight RGBW doesn't retain state after power cycling. (#2)

 

Hi Buckyfan

 

Yes I did have the BR30 working until I inadvertently bricked it by turning on the ESPhome verbose logging!  I attach my yaml with the verbose logging removed.  The header file needs to be the latest per digiblur post.

 

I have many Lohas 6” downlights which have exactly the same internal components and are working very well for me.

 

Were you able to tuya convert?  My device was purchased before the tuya update so the original tuya convert worked fine.  Several of my 6” downlights did not convert with the original tuya convert but the latest tuya convert worked OK.  My process was to tuya convert to Tasmoto, and use Tasmoto to download the esphome bin.

 

If you can give more detail of you exact process and problem I can perhaps help more?

**Comment by buckyfan** [comment]
Literally 10 minutes after I posed the question I figured it out LOL. I used digiblur's excellent Tuya Convert 2.3 guide from Youtube along with a donor D1 mini to flash two devices. Process initially failed when I burned the image and D1 mini in Ubuntu. As soon as I reflashed SD card and D1 in Windows it worked perfect. Flashed to Tasmota 7.0.0.1 then uploaded the .bin file.

This is the code i ended up using:
```
substitutions:
  display_name: Fireplace2
  
esphome:
  name: fireplace2
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: true
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
 
logger:

ota:

api:

switch:
  - platform: restart
    name: ${display_name} Restart

output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO5
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO4
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO13
  - platform: esp8266_pwm
    id: output_cold_white
    pin: GPIO14
  - platform: esp8266_pwm
    id: output_warm_white
    pin: GPIO12

light:
  - platform: rgbww
    name: ${display_name}
    red: output_red
    green: output_green
    blue: output_blue
    default_transition_length: 1s
    warm_white: output_warm_white
    cold_white: output_cold_white
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 2700 K
````
